version = 0.1
[default.deploy.parameters]
stack_name = "events-register-app"
resolve_s3 = true
s3_prefix = "events-register-app"
region = "eu-north-1"
profile = "AdministratorAccess-825925946567"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
